# Generated by Django 5.0.6 on 2024-05-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'контакт', 'verbose_name_plural': 'контакты'},
        ),
    ]
